"""Initial schema - calls, appointments, contacts, analytics, compliance

Revision ID: 25f951fb5996
Revises: 
Create Date: 2025-12-02 11:09:16.641370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '25f951fb5996'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_metrics',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(36), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('inbound_calls', sa.Integer(), nullable=False),
    sa.Column('outbound_calls', sa.Integer(), nullable=False),
    sa.Column('completed_calls', sa.Integer(), nullable=False),
    sa.Column('missed_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('transferred_calls', sa.Integer(), nullable=False),
    sa.Column('total_duration', sa.Integer(), nullable=False),
    sa.Column('avg_duration', sa.Float(), nullable=False),
    sa.Column('min_duration', sa.Integer(), nullable=False),
    sa.Column('max_duration', sa.Integer(), nullable=False),
    sa.Column('avg_wait_time', sa.Float(), nullable=False),
    sa.Column('max_wait_time', sa.Integer(), nullable=False),
    sa.Column('appointments_booked', sa.Integer(), nullable=False),
    sa.Column('appointments_modified', sa.Integer(), nullable=False),
    sa.Column('appointments_cancelled', sa.Integer(), nullable=False),
    sa.Column('service_calls_created', sa.Integer(), nullable=False),
    sa.Column('quotes_sent', sa.Integer(), nullable=False),
    sa.Column('ai_handled_calls', sa.Integer(), nullable=False),
    sa.Column('human_escalations', sa.Integer(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('appointment_conversion_rate', sa.Float(), nullable=False),
    sa.Column('ai_resolution_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'hour', 'industry', 'tenant_id', name='uq_call_metrics_period')
    )
    op.create_index(op.f('ix_call_metrics_date'), 'call_metrics', ['date'], unique=False)
    op.create_index('ix_call_metrics_date_industry', 'call_metrics', ['date', 'industry'], unique=False)
    op.create_index('ix_call_metrics_date_tenant', 'call_metrics', ['date', 'tenant_id'], unique=False)
    op.create_index(op.f('ix_call_metrics_hour'), 'call_metrics', ['hour'], unique=False)
    op.create_index(op.f('ix_call_metrics_industry'), 'call_metrics', ['industry'], unique=False)
    op.create_index(op.f('ix_call_metrics_tenant_id'), 'call_metrics', ['tenant_id'], unique=False)
    op.create_table('companies',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Official registered name'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='Steuernummer / USt-IdNr'),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('industry', sa.String(length=50), nullable=True, comment="Company's industry sector"),
    sa.Column('company_type', sa.String(length=50), nullable=True, comment='commercial, residential, public, etc.'),
    sa.Column('size', sa.String(length=20), nullable=True, comment='small, medium, large, enterprise'),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('total_service_calls', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_external_id'), 'companies', ['external_id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_index(op.f('ix_companies_phone'), 'companies', ['phone'], unique=False)
    op.create_index(op.f('ix_companies_zip_code'), 'companies', ['zip_code'], unique=False)
    op.create_table('contacts',
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('salutation', sa.String(length=20), nullable=True, comment='Herr, Frau, etc.'),
    sa.Column('phone_primary', sa.String(length=50), nullable=False),
    sa.Column('phone_secondary', sa.String(length=50), nullable=True),
    sa.Column('phone_mobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('street', sa.String(length=255), nullable=True),
    sa.Column('street_number', sa.String(length=20), nullable=True),
    sa.Column('zip_code', sa.String(length=10), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('contact_type', sa.String(length=50), nullable=False, comment='patient, customer, lead, prospect'),
    sa.Column('source', sa.String(length=50), nullable=True, comment='phone_agent, web, manual, import, referral'),
    sa.Column('industry', sa.String(length=50), nullable=False, comment='gesundheit, handwerk, freie_berufe, etc.'),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('insurance_type', sa.String(length=20), nullable=True, comment='GKV, PKV, Privat, Selbstzahler'),
    sa.Column('insurance_number', sa.String(length=50), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True, comment='residential, commercial, industrial'),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True, comment='phone, sms, email'),
    sa.Column('preferred_contact_time', sa.String(length=50), nullable=True, comment='morning, afternoon, evening'),
    sa.Column('preferred_language', sa.String(length=10), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_appointments', sa.Integer(), nullable=False),
    sa.Column('total_no_shows', sa.Integer(), nullable=False),
    sa.Column('first_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_appointment_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='ID in external PVS/CRM system'),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_primary', 'industry', name='uq_contact_phone_industry')
    )
    op.create_index(op.f('ix_contacts_contact_type'), 'contacts', ['contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_external_id'), 'contacts', ['external_id'], unique=False)
    op.create_index(op.f('ix_contacts_industry'), 'contacts', ['industry'], unique=False)
    op.create_index('ix_contacts_industry_type', 'contacts', ['industry', 'contact_type'], unique=False)
    op.create_index(op.f('ix_contacts_last_contact_at'), 'contacts', ['last_contact_at'], unique=False)
    op.create_index('ix_contacts_name', 'contacts', ['last_name', 'first_name'], unique=False)
    op.create_index(op.f('ix_contacts_phone_primary'), 'contacts', ['phone_primary'], unique=False)
    op.create_index(op.f('ix_contacts_zip_code'), 'contacts', ['zip_code'], unique=False)
    op.create_table('dashboard_snapshots',
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('snapshot_type', sa.String(length=16), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(36), nullable=True),
    sa.Column('calls_today', sa.Integer(), nullable=False),
    sa.Column('calls_this_week', sa.Integer(), nullable=False),
    sa.Column('calls_this_month', sa.Integer(), nullable=False),
    sa.Column('avg_call_duration', sa.Float(), nullable=False),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('ai_resolution_rate', sa.Float(), nullable=False),
    sa.Column('appointments_today', sa.Integer(), nullable=False),
    sa.Column('appointments_this_week', sa.Integer(), nullable=False),
    sa.Column('appointment_conversion_rate', sa.Float(), nullable=False),
    sa.Column('no_show_rate', sa.Float(), nullable=False),
    sa.Column('active_campaigns', sa.Integer(), nullable=False),
    sa.Column('campaign_contacts_reached', sa.Integer(), nullable=False),
    sa.Column('campaign_conversion_rate', sa.Float(), nullable=False),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('new_contacts_today', sa.Integer(), nullable=False),
    sa.Column('new_contacts_this_week', sa.Integer(), nullable=False),
    sa.Column('service_calls_today', sa.Integer(), nullable=False),
    sa.Column('quotes_sent_today', sa.Integer(), nullable=False),
    sa.Column('peak_hour', sa.Integer(), nullable=True),
    sa.Column('avg_wait_time', sa.Float(), nullable=False),
    sa.Column('missed_calls_today', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dashboard_snapshots_industry'), 'dashboard_snapshots', ['industry'], unique=False)
    op.create_index('ix_dashboard_snapshots_industry_time', 'dashboard_snapshots', ['industry', 'snapshot_at'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_snapshot_at'), 'dashboard_snapshots', ['snapshot_at'], unique=False)
    op.create_index(op.f('ix_dashboard_snapshots_tenant_id'), 'dashboard_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_dashboard_snapshots_type_time', 'dashboard_snapshots', ['snapshot_type', 'snapshot_at'], unique=False)
    op.create_table('data_retention_policies',
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('tenant_id', sa.String(36), nullable=True),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('archive_after_days', sa.Integer(), nullable=True),
    sa.Column('legal_basis', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_retention_policies_industry'), 'data_retention_policies', ['industry'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_resource_type'), 'data_retention_policies', ['resource_type'], unique=False)
    op.create_index(op.f('ix_data_retention_policies_tenant_id'), 'data_retention_policies', ['tenant_id'], unique=False)
    op.create_index('ix_retention_resource_industry', 'data_retention_policies', ['resource_type', 'industry'], unique=False)
    op.create_index('ix_retention_resource_tenant', 'data_retention_policies', ['resource_type', 'tenant_id'], unique=False)
    op.create_table('recall_campaigns',
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('campaign_type', sa.String(length=32), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(36), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('target_criteria_json', sa.Text(), nullable=True),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('call_interval_hours', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('call_script', sa.Text(), nullable=True),
    sa.Column('sms_template', sa.Text(), nullable=True),
    sa.Column('total_contacts', sa.Integer(), nullable=False),
    sa.Column('contacts_called', sa.Integer(), nullable=False),
    sa.Column('contacts_reached', sa.Integer(), nullable=False),
    sa.Column('appointments_booked', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recall_campaigns_campaign_type'), 'recall_campaigns', ['campaign_type'], unique=False)
    op.create_index(op.f('ix_recall_campaigns_industry'), 'recall_campaigns', ['industry'], unique=False)
    op.create_index('ix_recall_campaigns_industry_status', 'recall_campaigns', ['industry', 'status'], unique=False)
    op.create_index(op.f('ix_recall_campaigns_start_date'), 'recall_campaigns', ['start_date'], unique=False)
    op.create_index(op.f('ix_recall_campaigns_status'), 'recall_campaigns', ['status'], unique=False)
    op.create_index('ix_recall_campaigns_status_date', 'recall_campaigns', ['status', 'start_date'], unique=False)
    op.create_index(op.f('ix_recall_campaigns_tenant_id'), 'recall_campaigns', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('action_category', sa.String(length=32), nullable=True),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('contact_id', sa.String(36), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('previous_checksum', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_action_category'), 'audit_logs', ['action_category'], unique=False)
    op.create_index('ix_audit_logs_action_timestamp', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_contact_id'), 'audit_logs', ['contact_id'], unique=False)
    op.create_index('ix_audit_logs_contact_timestamp', 'audit_logs', ['contact_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_industry'), 'audit_logs', ['industry'], unique=False)
    op.create_index('ix_audit_logs_industry_timestamp', 'audit_logs', ['industry', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index('ix_audit_logs_resource_timestamp', 'audit_logs', ['resource_type', 'resource_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('calls',
    sa.Column('direction', sa.String(length=20), nullable=False, comment='inbound or outbound'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='incoming, ringing, active, on_hold, completed, missed, failed'),
    sa.Column('caller_id', sa.String(length=50), nullable=False, comment='Caller phone number'),
    sa.Column('callee_id', sa.String(length=50), nullable=False, comment='Callee phone number'),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True, comment='Full call transcript'),
    sa.Column('summary', sa.Text(), nullable=True, comment='AI-generated call summary'),
    sa.Column('triage_result', sa.String(length=100), nullable=True, comment='Triage urgency level'),
    sa.Column('appointment_id', sa.String(length=36), nullable=True, comment='Linked appointment UUID'),
    sa.Column('transferred', sa.Boolean(), nullable=False),
    sa.Column('transfer_to', sa.String(length=50), nullable=True, comment='Transfer destination'),
    sa.Column('transfer_reason', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True, comment='Additional call metadata'),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calls_caller_id'), 'calls', ['caller_id'], unique=False)
    op.create_index('ix_calls_caller_status', 'calls', ['caller_id', 'status'], unique=False)
    op.create_index(op.f('ix_calls_contact_id'), 'calls', ['contact_id'], unique=False)
    op.create_index(op.f('ix_calls_direction'), 'calls', ['direction'], unique=False)
    op.create_index(op.f('ix_calls_started_at'), 'calls', ['started_at'], unique=False)
    op.create_index('ix_calls_started_at_desc', 'calls', [sa.literal_column('started_at DESC')], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_table('campaign_metrics',
    sa.Column('campaign_id', sa.String(36), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('contacts_targeted', sa.Integer(), nullable=False),
    sa.Column('contacts_attempted', sa.Integer(), nullable=False),
    sa.Column('contacts_reached', sa.Integer(), nullable=False),
    sa.Column('contacts_converted', sa.Integer(), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('successful_calls', sa.Integer(), nullable=False),
    sa.Column('failed_calls', sa.Integer(), nullable=False),
    sa.Column('voicemail_left', sa.Integer(), nullable=False),
    sa.Column('no_answer', sa.Integer(), nullable=False),
    sa.Column('first_attempt_success', sa.Integer(), nullable=False),
    sa.Column('second_attempt_success', sa.Integer(), nullable=False),
    sa.Column('third_plus_attempt_success', sa.Integer(), nullable=False),
    sa.Column('total_talk_time', sa.Integer(), nullable=False),
    sa.Column('avg_call_duration', sa.Float(), nullable=False),
    sa.Column('appointments_booked', sa.Integer(), nullable=False),
    sa.Column('appointments_kept', sa.Integer(), nullable=False),
    sa.Column('appointments_no_show', sa.Integer(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=False),
    sa.Column('contact_rate', sa.Float(), nullable=False),
    sa.Column('conversion_rate', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('show_rate', sa.Float(), nullable=False),
    sa.Column('avg_attempts_to_reach', sa.Float(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['recall_campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'date', name='uq_campaign_metrics_date')
    )
    op.create_index('ix_campaign_metrics_campaign_date', 'campaign_metrics', ['campaign_id', 'date'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_campaign_id'), 'campaign_metrics', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_campaign_metrics_date'), 'campaign_metrics', ['date'], unique=False)
    op.create_table('consents',
    sa.Column('contact_id', sa.String(36), nullable=False),
    sa.Column('consent_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('industry', sa.String(length=32), nullable=True),
    sa.Column('reference_id', sa.String(36), nullable=True),
    sa.Column('reference_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('legal_text_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_consent_type'), 'consents', ['consent_type'], unique=False)
    op.create_index(op.f('ix_consents_contact_id'), 'consents', ['contact_id'], unique=False)
    op.create_index('ix_consents_contact_status', 'consents', ['contact_id', 'status'], unique=False)
    op.create_index('ix_consents_contact_type', 'consents', ['contact_id', 'consent_type'], unique=False)
    op.create_index(op.f('ix_consents_expires_at'), 'consents', ['expires_at'], unique=False)
    op.create_index('ix_consents_expiry', 'consents', ['expires_at', 'status'], unique=False)
    op.create_index(op.f('ix_consents_industry'), 'consents', ['industry'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_table('contact_company_links',
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True, comment='owner, manager, employee, contact_person'),
    sa.Column('job_title', sa.String(length=255), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False, comment='Primary contact for this company'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'company_id', name='uq_contact_company')
    )
    op.create_index(op.f('ix_contact_company_links_company_id'), 'contact_company_links', ['company_id'], unique=False)
    op.create_index(op.f('ix_contact_company_links_contact_id'), 'contact_company_links', ['contact_id'], unique=False)
    op.create_index('ix_link_company_primary', 'contact_company_links', ['company_id', 'is_primary'], unique=False)
    op.create_table('appointments',
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('patient_phone', sa.String(length=50), nullable=False),
    sa.Column('patient_email', sa.String(length=255), nullable=True),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('appointment_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False, comment='consultation, checkup, followup, emergency, vaccination, etc.'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='scheduled, confirmed, cancelled, completed, no_show'),
    sa.Column('provider_id', sa.String(length=100), nullable=True),
    sa.Column('provider_name', sa.String(length=255), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True, comment='Reason for appointment'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes'),
    sa.Column('reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=False, comment='phone_agent, web, manual, pvs_sync'),
    sa.Column('call_id', sa.String(length=36), nullable=True),
    sa.Column('contact_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_contact_id'), 'appointments', ['contact_id'], unique=False)
    op.create_index('ix_appointments_date_status', 'appointments', ['appointment_date', 'status'], unique=False)
    op.create_index(op.f('ix_appointments_patient_phone'), 'appointments', ['patient_phone'], unique=False)
    op.create_index('ix_appointments_provider_date', 'appointments', ['provider_id', 'appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_index(op.f('ix_appointments_type'), 'appointments', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_type'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_index('ix_appointments_provider_date', table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_phone'), table_name='appointments')
    op.drop_index('ix_appointments_date_status', table_name='appointments')
    op.drop_index(op.f('ix_appointments_contact_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index('ix_link_company_primary', table_name='contact_company_links')
    op.drop_index(op.f('ix_contact_company_links_contact_id'), table_name='contact_company_links')
    op.drop_index(op.f('ix_contact_company_links_company_id'), table_name='contact_company_links')
    op.drop_table('contact_company_links')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_industry'), table_name='consents')
    op.drop_index('ix_consents_expiry', table_name='consents')
    op.drop_index(op.f('ix_consents_expires_at'), table_name='consents')
    op.drop_index('ix_consents_contact_type', table_name='consents')
    op.drop_index('ix_consents_contact_status', table_name='consents')
    op.drop_index(op.f('ix_consents_contact_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_consent_type'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_campaign_metrics_date'), table_name='campaign_metrics')
    op.drop_index(op.f('ix_campaign_metrics_campaign_id'), table_name='campaign_metrics')
    op.drop_index('ix_campaign_metrics_campaign_date', table_name='campaign_metrics')
    op.drop_table('campaign_metrics')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index('ix_calls_started_at_desc', table_name='calls')
    op.drop_index(op.f('ix_calls_started_at'), table_name='calls')
    op.drop_index(op.f('ix_calls_direction'), table_name='calls')
    op.drop_index(op.f('ix_calls_contact_id'), table_name='calls')
    op.drop_index('ix_calls_caller_status', table_name='calls')
    op.drop_index(op.f('ix_calls_caller_id'), table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_industry_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_industry'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_contact_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_contact_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_recall_campaigns_tenant_id'), table_name='recall_campaigns')
    op.drop_index('ix_recall_campaigns_status_date', table_name='recall_campaigns')
    op.drop_index(op.f('ix_recall_campaigns_status'), table_name='recall_campaigns')
    op.drop_index(op.f('ix_recall_campaigns_start_date'), table_name='recall_campaigns')
    op.drop_index('ix_recall_campaigns_industry_status', table_name='recall_campaigns')
    op.drop_index(op.f('ix_recall_campaigns_industry'), table_name='recall_campaigns')
    op.drop_index(op.f('ix_recall_campaigns_campaign_type'), table_name='recall_campaigns')
    op.drop_table('recall_campaigns')
    op.drop_index('ix_retention_resource_tenant', table_name='data_retention_policies')
    op.drop_index('ix_retention_resource_industry', table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_tenant_id'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_resource_type'), table_name='data_retention_policies')
    op.drop_index(op.f('ix_data_retention_policies_industry'), table_name='data_retention_policies')
    op.drop_table('data_retention_policies')
    op.drop_index('ix_dashboard_snapshots_type_time', table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_tenant_id'), table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_snapshot_at'), table_name='dashboard_snapshots')
    op.drop_index('ix_dashboard_snapshots_industry_time', table_name='dashboard_snapshots')
    op.drop_index(op.f('ix_dashboard_snapshots_industry'), table_name='dashboard_snapshots')
    op.drop_table('dashboard_snapshots')
    op.drop_index(op.f('ix_contacts_zip_code'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_phone_primary'), table_name='contacts')
    op.drop_index('ix_contacts_name', table_name='contacts')
    op.drop_index(op.f('ix_contacts_last_contact_at'), table_name='contacts')
    op.drop_index('ix_contacts_industry_type', table_name='contacts')
    op.drop_index(op.f('ix_contacts_industry'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_external_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_contact_type'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_zip_code'), table_name='companies')
    op.drop_index(op.f('ix_companies_phone'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_external_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_call_metrics_tenant_id'), table_name='call_metrics')
    op.drop_index(op.f('ix_call_metrics_industry'), table_name='call_metrics')
    op.drop_index(op.f('ix_call_metrics_hour'), table_name='call_metrics')
    op.drop_index('ix_call_metrics_date_tenant', table_name='call_metrics')
    op.drop_index('ix_call_metrics_date_industry', table_name='call_metrics')
    op.drop_index(op.f('ix_call_metrics_date'), table_name='call_metrics')
    op.drop_table('call_metrics')
    # ### end Alembic commands ###
