"""add_multi_tenant_models

Revision ID: 2b8806bd7f12
Revises: fdb7dfd4116b
Create Date: 2025-12-16 02:37:30.159465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# Import our custom UUID type for proper UUID handling
from phone_agent.db.base import UUIDType

# revision identifiers, used by Alembic.
revision: str = '2b8806bd7f12'
down_revision: Union[str, Sequence[str], None] = 'fdb7dfd4116b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment="Display name (e.g., 'Müller SHK')"),
    sa.Column('legal_name', sa.String(length=255), nullable=True, comment='Official registered name'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='Steuernummer / USt-IdNr'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment="URL-safe identifier (e.g., 'mueller-shk')"),
    sa.Column('industry', sa.String(length=50), nullable=False, comment='Industry module: handwerk, gesundheit, freie_berufe, gastro'),
    sa.Column('trade_category', sa.String(length=50), nullable=True, comment='Handwerk: shk, elektro, sanitaer, klima, etc.'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True, comment='PLZ for radius calculation'),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('address_country', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True, comment='Pre-geocoded latitude'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='Pre-geocoded longitude'),
    sa.Column('service_radius_km', sa.Integer(), nullable=False, comment='Service area radius in kilometers'),
    sa.Column('plan', sa.String(length=50), nullable=False, comment='Subscription plan: starter, professional, enterprise'),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('max_tasks_per_month', sa.Integer(), nullable=False),
    sa.Column('max_storage_gb', sa.Integer(), nullable=False),
    sa.Column('current_users', sa.Integer(), nullable=False),
    sa.Column('current_tasks_this_month', sa.Integer(), nullable=False),
    sa.Column('current_storage_gb', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False, comment='active, suspended, trial, cancelled'),
    sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settings_json', sqlite.JSON(), nullable=True, comment='Routing rules, feature flags, prompts overrides'),
    sa.Column('branding_json', sqlite.JSON(), nullable=True, comment='Logo URL, colors, custom domain'),
    sa.Column('email_config_json', sqlite.JSON(), nullable=True, comment='IMAP polling configuration (encrypted password)'),
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_address_zip'), 'tenants', ['address_zip'], unique=False)
    op.create_index(op.f('ix_tenants_industry'), 'tenants', ['industry'], unique=False)
    op.create_index('ix_tenants_industry_status', 'tenants', ['industry', 'status'], unique=False)
    op.create_index(op.f('ix_tenants_name'), 'tenants', ['name'], unique=False)
    op.create_index(op.f('ix_tenants_phone'), 'tenants', ['phone'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_index(op.f('ix_tenants_status'), 'tenants', ['status'], unique=False)
    op.create_index('ix_tenants_zip_radius', 'tenants', ['address_zip', 'service_radius_km'], unique=False)
    op.create_table('departments',
    sa.Column('tenant_id', UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment="Display name (e.g., 'Kundendienst')"),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('handles_task_types', sqlite.JSON(), nullable=True, comment='Task types this dept handles: ["repairs", "quotes", "complaints"]'),
    sa.Column('handles_urgency_levels', sqlite.JSON(), nullable=True, comment='Urgency levels: ["notfall", "dringend", "normal"]'),
    sa.Column('handles_trade_categories', sqlite.JSON(), nullable=True, comment='Trade categories: ["shk", "elektro"]'),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('working_hours', sqlite.JSON(), nullable=True, comment='{"monday": "08:00-17:00", "tuesday": "08:00-17:00", ...}'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_departments_tenant_active', 'departments', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('workers',
    sa.Column('tenant_id', UUIDType(), nullable=False),
    sa.Column('department_id', UUIDType(), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False, comment='owner, admin, dispatcher, worker'),
    sa.Column('trade_categories', sqlite.JSON(), nullable=True, comment='Skills: ["shk", "elektro", "sanitaer"]'),
    sa.Column('certifications', sqlite.JSON(), nullable=True, comment='Certifications: ["gas_certified", "electrical_license"]'),
    sa.Column('home_plz', sa.String(length=10), nullable=True, comment='Home postal code for route optimization'),
    sa.Column('home_latitude', sa.Float(), nullable=True),
    sa.Column('home_longitude', sa.Float(), nullable=True),
    sa.Column('working_hours', sqlite.JSON(), nullable=True, comment='{"monday": "08:00-17:00", ...}'),
    sa.Column('vacation_dates', sqlite.JSON(), nullable=True, comment='["2025-01-20", "2025-01-21"]'),
    sa.Column('max_tasks_per_day', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_tasks_completed', sa.Integer(), nullable=False),
    sa.Column('avg_completion_time_minutes', sa.Float(), nullable=True),
    sa.Column('customer_rating', sa.Float(), nullable=True, comment='Average rating 1.0-5.0'),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='ID in external HR/ERP system'),
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workers_department_id'), 'workers', ['department_id'], unique=False)
    op.create_index(op.f('ix_workers_email'), 'workers', ['email'], unique=False)
    op.create_index('ix_workers_tenant_active', 'workers', ['tenant_id', 'is_active'], unique=False)
    op.create_index('ix_workers_tenant_department', 'workers', ['tenant_id', 'department_id'], unique=False)
    op.create_index(op.f('ix_workers_tenant_id'), 'workers', ['tenant_id'], unique=False)
    op.create_table('routing_rules',
    sa.Column('tenant_id', UUIDType(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='Human-readable rule name'),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False, comment='Lower numbers are evaluated first'),
    sa.Column('conditions', sqlite.JSON(), nullable=False, comment='{"task_type": "repairs", "urgency": ["notfall", "dringend"]}'),
    sa.Column('route_to_department_id', UUIDType(), nullable=True),
    sa.Column('route_to_worker_id', UUIDType(), nullable=True),
    sa.Column('set_priority', sa.Integer(), nullable=True, comment='Override routing_priority'),
    sa.Column('send_notification', sa.Boolean(), nullable=False),
    sa.Column('notification_channels', sqlite.JSON(), nullable=True, comment='["sms", "email", "push"]'),
    sa.Column('escalate_after_minutes', sa.Integer(), nullable=True, comment='Escalate if not handled within X minutes'),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['route_to_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_to_worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_routing_rules_tenant_active', 'routing_rules', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_routing_rules_tenant_id'), 'routing_rules', ['tenant_id'], unique=False)
    op.create_index('ix_routing_rules_tenant_priority', 'routing_rules', ['tenant_id', 'priority'], unique=False)
    op.create_table('tasks',
    sa.Column('tenant_id', UUIDType(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='phone, email, form, whatsapp, manual'),
    sa.Column('source_id', sa.String(length=100), nullable=True, comment='Reference to original call_id, email_id, etc.'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='repairs, quotes, complaints, billing, appointment, general'),
    sa.Column('urgency', sa.String(length=20), nullable=False, comment='notfall, dringend, normal, routine'),
    sa.Column('trade_category', sa.String(length=50), nullable=True, comment='shk, elektro, sanitaer, etc.'),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_address', sa.Text(), nullable=True),
    sa.Column('customer_plz', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Short summary of the task'),
    sa.Column('description', sa.Text(), nullable=True, comment='Full description from customer'),
    sa.Column('ai_summary', sa.Text(), nullable=True, comment='AI-generated summary'),
    sa.Column('attachments_json', sqlite.JSON(), nullable=True, comment='[{"filename": "...", "url": "...", "type": "image/jpeg"}]'),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('distance_from_hq_km', sa.Float(), nullable=True, comment='Pre-calculated distance from tenant HQ'),
    sa.Column('routing_priority', sa.Integer(), nullable=False, comment='Lower = higher priority (0=notfall, 50=dringend, 100=normal)'),
    sa.Column('routing_reason', sa.Text(), nullable=True, comment='Why was this routed here'),
    sa.Column('assigned_department_id', UUIDType(), nullable=True),
    sa.Column('assigned_worker_id', UUIDType(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by', sa.String(length=100), nullable=True, comment='auto_routing, manual:worker_id'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='new, assigned, in_progress, completed, cancelled'),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal notes from workers'),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', UUIDType(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_worker_id'], ['workers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tasks_assigned', 'tasks', ['tenant_id', 'assigned_worker_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_department_id'), 'tasks', ['assigned_department_id'], unique=False)
    op.create_index(op.f('ix_tasks_assigned_worker_id'), 'tasks', ['assigned_worker_id'], unique=False)
    op.create_index(op.f('ix_tasks_customer_phone'), 'tasks', ['customer_phone'], unique=False)
    op.create_index(op.f('ix_tasks_customer_plz'), 'tasks', ['customer_plz'], unique=False)
    op.create_index(op.f('ix_tasks_source_type'), 'tasks', ['source_type'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_tenant_id'), 'tasks', ['tenant_id'], unique=False)
    op.create_index('ix_tasks_tenant_routing', 'tasks', ['tenant_id', 'routing_priority', 'created_at'], unique=False)
    op.create_index('ix_tasks_tenant_status', 'tasks', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_tasks_tenant_type_status', 'tasks', ['tenant_id', 'task_type', 'status'], unique=False)
    op.create_index('ix_tasks_tenant_urgency', 'tasks', ['tenant_id', 'urgency'], unique=False)
    op.create_index(op.f('ix_tasks_urgency'), 'tasks', ['urgency'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_urgency'), table_name='tasks')
    op.drop_index('ix_tasks_tenant_urgency', table_name='tasks')
    op.drop_index('ix_tasks_tenant_type_status', table_name='tasks')
    op.drop_index('ix_tasks_tenant_status', table_name='tasks')
    op.drop_index('ix_tasks_tenant_routing', table_name='tasks')
    op.drop_index(op.f('ix_tasks_tenant_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_source_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_plz'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_phone'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_worker_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_department_id'), table_name='tasks')
    op.drop_index('ix_tasks_assigned', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_routing_rules_tenant_priority', table_name='routing_rules')
    op.drop_index(op.f('ix_routing_rules_tenant_id'), table_name='routing_rules')
    op.drop_index('ix_routing_rules_tenant_active', table_name='routing_rules')
    op.drop_table('routing_rules')
    op.drop_index(op.f('ix_workers_tenant_id'), table_name='workers')
    op.drop_index('ix_workers_tenant_department', table_name='workers')
    op.drop_index('ix_workers_tenant_active', table_name='workers')
    op.drop_index(op.f('ix_workers_email'), table_name='workers')
    op.drop_index(op.f('ix_workers_department_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index('ix_departments_tenant_active', table_name='departments')
    op.drop_table('departments')
    op.drop_index('ix_tenants_zip_radius', table_name='tenants')
    op.drop_index(op.f('ix_tenants_status'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_phone'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_name'), table_name='tenants')
    op.drop_index('ix_tenants_industry_status', table_name='tenants')
    op.drop_index(op.f('ix_tenants_industry'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_address_zip'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
