"""Add CampaignContactModel for recall campaign contacts

Revision ID: b6641af6f696
Revises: 25f951fb5996
Create Date: 2025-12-02 13:34:55.548413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6641af6f696'
down_revision: Union[str, Sequence[str], None] = '25f951fb5996'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_contacts',
    sa.Column('campaign_id', sa.String(length=36), nullable=False),
    sa.Column('contact_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_call_result', sa.String(length=32), nullable=True),
    sa.Column('last_call_duration', sa.Integer(), nullable=True),
    sa.Column('last_call_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=True),
    sa.Column('appointment_id', sa.String(length=36), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('contact_name', sa.String(length=128), nullable=True),
    sa.Column('custom_data_json', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('opted_out', sa.Boolean(), nullable=False),
    sa.Column('opted_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['recall_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'contact_id', name='uq_campaign_contact')
    )
    op.create_index(op.f('ix_campaign_contacts_campaign_id'), 'campaign_contacts', ['campaign_id'], unique=False)
    op.create_index('ix_campaign_contacts_campaign_status', 'campaign_contacts', ['campaign_id', 'status'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_contact_id'), 'campaign_contacts', ['contact_id'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_next_attempt_at'), 'campaign_contacts', ['next_attempt_at'], unique=False)
    op.create_index('ix_campaign_contacts_phone', 'campaign_contacts', ['phone_number'], unique=False)
    op.create_index(op.f('ix_campaign_contacts_status'), 'campaign_contacts', ['status'], unique=False)
    op.create_index('ix_campaign_contacts_status_next', 'campaign_contacts', ['status', 'next_attempt_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_campaign_contacts_status_next', table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_status'), table_name='campaign_contacts')
    op.drop_index('ix_campaign_contacts_phone', table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_next_attempt_at'), table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_contact_id'), table_name='campaign_contacts')
    op.drop_index('ix_campaign_contacts_campaign_status', table_name='campaign_contacts')
    op.drop_index(op.f('ix_campaign_contacts_campaign_id'), table_name='campaign_contacts')
    op.drop_table('campaign_contacts')
    # ### end Alembic commands ###
