"""add_handwerk_jobs_quotes

Revision ID: fdb7dfd4116b
Revises: b6641af6f696
Create Date: 2025-12-06 03:36:33.959844

"""
from typing import Sequence, Union
import sys
import os

# Add src to path for imports
sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "..", "src"))

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite
from phone_agent.db.base import UUIDType

# revision identifiers, used by Alembic.
revision: str = 'fdb7dfd4116b'
down_revision: Union[str, Sequence[str], None] = 'b6641af6f696'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_messages',
    sa.Column('to_email', sa.String(length=255), nullable=False, comment='Primary recipient email address'),
    sa.Column('to_emails_json', sqlite.JSON(), nullable=True, comment='All recipient emails (to, cc, bcc)'),
    sa.Column('from_email', sa.String(length=255), nullable=True, comment='Sender email address'),
    sa.Column('from_name', sa.String(length=255), nullable=True, comment='Sender display name'),
    sa.Column('reply_to', sa.String(length=255), nullable=True, comment='Reply-to email address'),
    sa.Column('subject', sa.String(length=500), nullable=False, comment='Email subject'),
    sa.Column('body_text', sa.Text(), nullable=True, comment='Plain text body'),
    sa.Column('body_html', sa.Text(), nullable=True, comment='HTML body'),
    sa.Column('has_attachments', sa.Boolean(), nullable=False, comment='Whether email has attachments'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='Email provider: smtp, sendgrid, mock'),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True, comment='External message ID from provider'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='pending, queued, sent, delivered, opened, clicked, bounced, failed'),
    sa.Column('error_code', sa.String(length=50), nullable=True, comment='Provider error code if failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error description if failed'),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True, comment='When message was queued for sending'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When message was sent'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='When message was delivered'),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True, comment='When message was first opened'),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True, comment='When message link was first clicked'),
    sa.Column('bounced_at', sa.DateTime(timezone=True), nullable=True, comment='When message bounced'),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True, comment='When message delivery failed'),
    sa.Column('open_count', sa.Integer(), nullable=False, comment='Number of times email was opened'),
    sa.Column('click_count', sa.Integer(), nullable=False, comment='Number of link clicks'),
    sa.Column('last_opened_at', sa.DateTime(timezone=True), nullable=True, comment='Last time email was opened'),
    sa.Column('last_clicked_at', sa.DateTime(timezone=True), nullable=True, comment='Last time link was clicked'),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='confirmation, reminder, cancellation, notification, marketing'),
    sa.Column('reference', sa.String(length=255), nullable=True, comment='External reference ID for correlation'),
    sa.Column('tags_json', sqlite.JSON(), nullable=True, comment='Tags for categorization'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of send attempts'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum retry attempts'),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='Next retry attempt time'),
    sa.Column('appointment_id', sa.String(length=36), nullable=True, comment='Linked appointment UUID'),
    sa.Column('contact_id', sa.String(length=36), nullable=True, comment='Linked contact UUID'),
    sa.Column('webhook_received', sa.Integer(), nullable=False, comment='Number of status webhooks received'),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True, comment='Last webhook received timestamp'),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True, comment='Additional message metadata'),
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_messages_appointment_id'), 'email_messages', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_email_messages_contact_id'), 'email_messages', ['contact_id'], unique=False)
    op.create_index('ix_email_messages_created_status', 'email_messages', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_email_messages_message_type'), 'email_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_email_messages_provider'), 'email_messages', ['provider'], unique=False)
    op.create_index(op.f('ix_email_messages_provider_message_id'), 'email_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_email_messages_reference'), 'email_messages', ['reference'], unique=False)
    op.create_index('ix_email_messages_retry', 'email_messages', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_email_messages_status'), 'email_messages', ['status'], unique=False)
    op.create_index('ix_email_messages_status_provider', 'email_messages', ['status', 'provider'], unique=False)
    op.create_index(op.f('ix_email_messages_to_email'), 'email_messages', ['to_email'], unique=False)
    op.create_index('ix_email_messages_to_email_created', 'email_messages', ['to_email', 'created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('job_number', sa.String(length=50), nullable=False, comment='Human-readable job number (e.g., JOB-2024-0001)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='Brief description of the job'),
    sa.Column('description', sa.Text(), nullable=True, comment='Detailed description of work needed'),
    sa.Column('trade_category', sa.String(length=50), nullable=False, comment='Trade type: shk, elektro, schlosser, etc.'),
    sa.Column('urgency', sa.String(length=50), nullable=False, comment='Urgency level from triage: notfall, dringend, normal, routine'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Current job status'),
    sa.Column('address_street', sa.String(length=255), nullable=True),
    sa.Column('address_number', sa.String(length=20), nullable=True),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('address_city', sa.String(length=100), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True, comment='residential, commercial, industrial'),
    sa.Column('access_notes', sa.Text(), nullable=True, comment='Access instructions, parking info, etc.'),
    sa.Column('preferred_date', sa.Date(), nullable=True, comment="Customer's preferred date"),
    sa.Column('preferred_time_window', sa.String(length=50), nullable=True, comment='Time window: frueh, vormittag, mittag, nachmittag, spaet, abend'),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('estimated_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True, comment='When technician started work'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='When work was completed'),
    sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Estimated cost before work'),
    sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True, comment='Actual cost after completion'),
    sa.Column('is_paid', sa.Boolean(), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('customer_notes', sa.Text(), nullable=True, comment='Notes from customer about the job'),
    sa.Column('technician_notes', sa.Text(), nullable=True, comment='Notes from technician after work'),
    sa.Column('internal_notes', sa.Text(), nullable=True, comment='Internal office notes'),
    sa.Column('materials_json', sqlite.JSON(), nullable=True, comment='Materials used: [{name, quantity, cost}]'),
    sa.Column('contact_id', UUIDType(length=36), nullable=True, comment='Customer who requested the job'),
    sa.Column('technician_id', UUIDType(length=36), nullable=True, comment='Assigned technician'),
    sa.Column('appointment_id', UUIDType(length=36), nullable=True, comment='Linked appointment for scheduling'),
    sa.Column('call_id', UUIDType(length=36), nullable=True, comment='Originating phone call'),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_contact_id'), 'jobs', ['contact_id'], unique=False)
    op.create_index(op.f('ix_jobs_job_number'), 'jobs', ['job_number'], unique=True)
    op.create_index(op.f('ix_jobs_scheduled_date'), 'jobs', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_status_date', 'jobs', ['status', 'scheduled_date'], unique=False)
    op.create_index(op.f('ix_jobs_technician_id'), 'jobs', ['technician_id'], unique=False)
    op.create_index(op.f('ix_jobs_trade_category'), 'jobs', ['trade_category'], unique=False)
    op.create_index('ix_jobs_trade_status', 'jobs', ['trade_category', 'status'], unique=False)
    op.create_index(op.f('ix_jobs_urgency'), 'jobs', ['urgency'], unique=False)
    op.create_index('ix_jobs_urgency_status', 'jobs', ['urgency', 'status'], unique=False)
    op.create_table('sms_messages',
    sa.Column('to_number', sa.String(length=50), nullable=False, comment='Recipient phone number in E.164 format'),
    sa.Column('from_number', sa.String(length=50), nullable=True, comment='Sender phone number or ID'),
    sa.Column('body', sa.Text(), nullable=False, comment='SMS message body'),
    sa.Column('segments', sa.Integer(), nullable=False, comment='Number of SMS segments'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='SMS provider: twilio, sipgate, mock'),
    sa.Column('provider_message_id', sa.String(length=100), nullable=True, comment='External message ID from provider'),
    sa.Column('status', sa.String(length=30), nullable=False, comment='pending, queued, sent, delivered, failed, undelivered'),
    sa.Column('error_code', sa.String(length=20), nullable=True, comment='Provider error code if failed'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error description if failed'),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True, comment='When message was queued for sending'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='When message was sent to carrier'),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True, comment='When message was delivered to recipient'),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True, comment='When message delivery failed'),
    sa.Column('cost', sa.Float(), nullable=True, comment='Message cost in EUR'),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('message_type', sa.String(length=50), nullable=False, comment='confirmation, reminder, cancellation, notification, marketing'),
    sa.Column('reference', sa.String(length=255), nullable=True, comment='External reference ID for correlation'),
    sa.Column('retry_count', sa.Integer(), nullable=False, comment='Number of send attempts'),
    sa.Column('max_retries', sa.Integer(), nullable=False, comment='Maximum retry attempts'),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True, comment='Next retry attempt time'),
    sa.Column('appointment_id', sa.String(length=36), nullable=True, comment='Linked appointment UUID'),
    sa.Column('contact_id', sa.String(length=36), nullable=True, comment='Linked contact UUID'),
    sa.Column('call_id', sa.String(length=36), nullable=True, comment='Linked call UUID'),
    sa.Column('webhook_received', sa.Integer(), nullable=False, comment='Number of status webhooks received'),
    sa.Column('last_webhook_at', sa.DateTime(timezone=True), nullable=True, comment='Last webhook received timestamp'),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True, comment='Additional message metadata'),
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_messages_appointment_id'), 'sms_messages', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_call_id'), 'sms_messages', ['call_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_contact_id'), 'sms_messages', ['contact_id'], unique=False)
    op.create_index('ix_sms_messages_created_status', 'sms_messages', ['created_at', 'status'], unique=False)
    op.create_index(op.f('ix_sms_messages_message_type'), 'sms_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_sms_messages_provider'), 'sms_messages', ['provider'], unique=False)
    op.create_index(op.f('ix_sms_messages_provider_message_id'), 'sms_messages', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_sms_messages_reference'), 'sms_messages', ['reference'], unique=False)
    op.create_index('ix_sms_messages_retry', 'sms_messages', ['status', 'next_retry_at'], unique=False)
    op.create_index(op.f('ix_sms_messages_status'), 'sms_messages', ['status'], unique=False)
    op.create_index('ix_sms_messages_status_provider', 'sms_messages', ['status', 'provider'], unique=False)
    op.create_index(op.f('ix_sms_messages_to_number'), 'sms_messages', ['to_number'], unique=False)
    op.create_index('ix_sms_messages_to_number_created', 'sms_messages', ['to_number', 'created_at'], unique=False)
    op.create_table('quotes',
    sa.Column('quote_number', sa.String(length=50), nullable=False, comment='Human-readable quote number (e.g., QUO-2024-0001)'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Version number for revised quotes'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='draft, sent, accepted, rejected, expired, revised'),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_until', sa.Date(), nullable=False, comment='Quote expiration date'),
    sa.Column('items_json', sqlite.JSON(), nullable=False, comment='Line items: [{description, quantity, unit, unit_price, total}]'),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=False, comment='Tax rate percentage (e.g., 19.0 for 19% MwSt)'),
    sa.Column('tax_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_terms', sa.Text(), nullable=True, comment='Payment terms and conditions'),
    sa.Column('notes', sa.Text(), nullable=True, comment='Additional notes on the quote'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True, comment='When customer viewed the quote'),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('job_id', UUIDType(length=36), nullable=False),
    sa.Column('contact_id', UUIDType(length=36), nullable=True),
    sa.Column('created_by_id', UUIDType(length=36), nullable=True, comment='Staff member who created the quote'),
    sa.Column('metadata_json', sqlite.JSON(), nullable=True),
    sa.Column('id', UUIDType(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotes_contact_id'), 'quotes', ['contact_id'], unique=False)
    op.create_index(op.f('ix_quotes_job_id'), 'quotes', ['job_id'], unique=False)
    op.create_index('ix_quotes_job_version', 'quotes', ['job_id', 'version'], unique=False)
    op.create_index(op.f('ix_quotes_quote_number'), 'quotes', ['quote_number'], unique=True)
    op.create_index(op.f('ix_quotes_status'), 'quotes', ['status'], unique=False)
    op.create_index('ix_quotes_status_valid', 'quotes', ['status', 'valid_until'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_quotes_status_valid', table_name='quotes')
    op.drop_index(op.f('ix_quotes_status'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_quote_number'), table_name='quotes')
    op.drop_index('ix_quotes_job_version', table_name='quotes')
    op.drop_index(op.f('ix_quotes_job_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_contact_id'), table_name='quotes')
    op.drop_table('quotes')
    op.drop_index('ix_sms_messages_to_number_created', table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_to_number'), table_name='sms_messages')
    op.drop_index('ix_sms_messages_status_provider', table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_status'), table_name='sms_messages')
    op.drop_index('ix_sms_messages_retry', table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_reference'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_provider_message_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_provider'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_message_type'), table_name='sms_messages')
    op.drop_index('ix_sms_messages_created_status', table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_contact_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_call_id'), table_name='sms_messages')
    op.drop_index(op.f('ix_sms_messages_appointment_id'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index('ix_jobs_urgency_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_urgency'), table_name='jobs')
    op.drop_index('ix_jobs_trade_status', table_name='jobs')
    op.drop_index(op.f('ix_jobs_trade_category'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_technician_id'), table_name='jobs')
    op.drop_index('ix_jobs_status_date', table_name='jobs')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_scheduled_date'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_number'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_contact_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_email_messages_to_email_created', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_to_email'), table_name='email_messages')
    op.drop_index('ix_email_messages_status_provider', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_status'), table_name='email_messages')
    op.drop_index('ix_email_messages_retry', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_reference'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider_message_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_provider'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_message_type'), table_name='email_messages')
    op.drop_index('ix_email_messages_created_status', table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_contact_id'), table_name='email_messages')
    op.drop_index(op.f('ix_email_messages_appointment_id'), table_name='email_messages')
    op.drop_table('email_messages')
    # ### end Alembic commands ###
