"""Elektro-Betrieb specific ORM Models.

Contains models specific to electrician company operations:
- ConversationTranscriptModel: Stores voice conversation history linked to jobs
"""
from __future__ import annotations

from datetime import datetime
from typing import TYPE_CHECKING, Any
from uuid import UUID

from sqlalchemy import (
    String,
    Text,
    Integer,
    DateTime,
    ForeignKey,
    Index,
)
from sqlalchemy.dialects.sqlite import JSON
from sqlalchemy.orm import Mapped, mapped_column, relationship

from phone_agent.db.base import Base, UUIDMixin, TimestampMixin

if TYPE_CHECKING:
    from phone_agent.db.models.handwerk import JobModel


class ConversationTranscriptModel(Base, UUIDMixin, TimestampMixin):
    """Voice conversation transcript storage.

    Stores the full conversation history from voice demo sessions,
    linked to the resulting job for reference in the admin dashboard.
    """

    __tablename__ = "conversation_transcripts"

    # Session identification
    session_id: Mapped[str] = mapped_column(
        String(100),
        unique=True,
        nullable=False,
        index=True,
        comment="Voice demo session ID",
    )

    # Language of conversation
    language: Mapped[str] = mapped_column(
        String(10),
        nullable=False,
        default="de",
        comment="Primary language: de, ru, tr, en",
    )

    # Conversation content
    turns_json: Mapped[list[dict[str, Any]]] = mapped_column(
        JSON,
        nullable=False,
        default=list,
        comment="Conversation turns: [{role, content, timestamp, language}, ...]",
    )

    # AI-detected information
    urgency_detected: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        comment="Detected urgency: notfall, dringend, normal, routine",
    )
    trade_detected: Mapped[str | None] = mapped_column(
        String(20),
        nullable=True,
        default="elektro",
        comment="Detected trade category",
    )

    # Conversation metadata
    turn_count: Mapped[int] = mapped_column(
        Integer,
        default=0,
        nullable=False,
        comment="Number of conversation turns",
    )
    duration_seconds: Mapped[int | None] = mapped_column(
        Integer,
        nullable=True,
        comment="Total conversation duration",
    )

    # Summary generated by AI
    summary: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="AI-generated conversation summary",
    )

    # Customer problem description (extracted)
    problem_description: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
        comment="Extracted problem description for job",
    )

    # Foreign keys
    job_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("jobs.id"),
        nullable=True,
        index=True,
        comment="Linked job created from this conversation",
    )

    # Relationships
    job: Mapped["JobModel | None"] = relationship(
        "JobModel",
        back_populates="transcript",
        foreign_keys=[job_id],
    )

    # Indexes for dashboard queries
    __table_args__ = (
        Index("ix_transcripts_created", "created_at"),
        Index("ix_transcripts_urgency", "urgency_detected"),
    )

    def add_turn(
        self,
        role: str,
        content: str,
        language: str = "de",
        timestamp: datetime | None = None,
    ) -> None:
        """Add a conversation turn.

        Args:
            role: 'user' or 'assistant'
            content: Message content
            language: Language of this turn
            timestamp: When the turn occurred
        """
        if self.turns_json is None:
            self.turns_json = []

        self.turns_json.append({
            "role": role,
            "content": content,
            "language": language,
            "timestamp": (timestamp or datetime.now()).isoformat(),
        })
        self.turn_count = len(self.turns_json)

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for API responses."""
        return {
            "id": str(self.id),
            "session_id": self.session_id,
            "language": self.language,
            "turns": self.turns_json,
            "turn_count": self.turn_count,
            "urgency_detected": self.urgency_detected,
            "trade_detected": self.trade_detected,
            "duration_seconds": self.duration_seconds,
            "summary": self.summary,
            "problem_description": self.problem_description,
            "job_id": str(self.job_id) if self.job_id else None,
            "created_at": self.created_at.isoformat() if self.created_at else None,
        }
